apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-main
  namespace: monitoring

---
apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KcmVjZWl2ZXJzOgogIC0gbmFtZTogd2VjaGF0LXJlY2VpdmVyCiAgICB3ZWJob29rX2NvbmZpZ3M6CiAgICAgIC0gdXJsOiBodHRwOi8vMTcyLjE2LjIwOC4xMzo3Nzc3L3Byb21ldGhldXMKcm91dGU6CiAgcmVjZWl2ZXI6ICd3ZWNoYXQtcmVjZWl2ZXInCiAgZ3JvdXBfd2FpdDogMXMKICBncm91cF9pbnRlcnZhbDogMzYwMHMKICByZXBlYXRfaW50ZXJ2YWw6IDM2MDBzCiAgcm91dGVzOgogIC0gcmVjZWl2ZXI6ICd3ZWNoYXQtcmVjZWl2ZXInCg==
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque

---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 1
  serviceAccountName: alertmanager-main
  version: v0.15.0
  storage:
    volumeClaimTemplate:
      metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: rook-ceph-block
      spec:
        resources:
          requests:
            storage: 5Gi


---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-main
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    alertmanager: main
    app: alertmanager

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      alertmanager: main
