kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  proxy-buffer-size: 128k
  log-format-escape-json: 'true'
  log-format-upstream: >-
    {"@timestamp": "$time_iso8601",
    "remote_addr": "$remote_addr",
    "http_x_forwarded_for": "$http_x_forwarded_for",
    "x-forward-for": "$proxy_add_x_forwarded_for",
    "request_id": "$request_id",
    "real_ip": "$the_real_ip",
    "remote_user": "$remote_user",
    "bytes_sent": $bytes_sent,
    "status": $status,
    "content_length": "$content_length",
    "scheme":"$scheme",
    "vhost": "$host",
    "request_proto": "$server_protocol",
    "path": "$uri",
    "request_uri": "$request_uri",
    "request_query": "$args",
    "request_length": $request_length,
    "duration": $request_time,
    "method": "$request_method",
    "http_referer": "$http_referer",
    "http_client_source": "$http_client_source",
    "http_client_version": "$http_client_version",
    "http_user_agent": "$http_user_agent",
    "http_token": "$http_authorization",
    "cookie_token": "$cookie_access_token",
    "cookie_uid": "$cookie_uid",
    "k8s_ingress_name": "$ingress_name",
    "k8s_namespace": "$namespace",
    "k8s_service_name": "$service_name",
    "upstream_name": "$proxy_upstream_name",
    "upstream_addr": "$upstream_addr",
    "upstream_status": "$upstream_status",
    "upstream_response_time": "$upstream_response_time"}
